#!/usr/bin/env node

/**
 * Build script to generate prompts.ts from markdown files.
 * This allows prompts to be edited as markdown files and then
 * bundled into the plugin at build time.
 */

const fs = require("fs");
const path = require("path");

const promptsDir = path.join(__dirname, "..", "prompts");
const outputFile = path.join(__dirname, "..", "src", "prompts.ts");

const promptFiles = [
  { key: "meetingFilter", file: "meeting-filter.md" },
  { key: "meetingBriefing", file: "meeting-briefing.md" },
  { key: "personResearch", file: "person-research.md" },
  { key: "orgResearch", file: "org-research.md" },
  { key: "inboxRouting", file: "inbox-routing.md" },
  { key: "research", file: "research.md" },
];

console.log("[GSD] Generating prompts.ts from markdown files...");

const prompts = {};

for (const { key, file } of promptFiles) {
  const filePath = path.join(promptsDir, file);
  
  if (!fs.existsSync(filePath)) {
    console.warn(`Warning: Prompt file not found: ${filePath}`);
    prompts[key] = "";
    continue;
  }

  const content = fs.readFileSync(filePath, "utf-8");
  // Escape backticks and template literals for use in template string
  const escaped = content
    .trimEnd()
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\${/g, "\\${");
  
  prompts[key] = escaped;
  console.log(`  ✓ Loaded ${file}`);
}

// Generate the TypeScript file
const tsContent = `/**
 * Prompts loaded from markdown files.
 * 
 * This file is auto-generated by scripts/generate-prompts.js
 * DO NOT EDIT THIS FILE DIRECTLY.
 * 
 * To update prompts, edit the .md files in the prompts/ directory
 * and run: npm run generate-prompts
 * 
 * Or rebuild the plugin, which will automatically regenerate this file.
 */

export const PROMPTS = {
  meetingFilter: \`${prompts.meetingFilter}\`,
  meetingBriefing: \`${prompts.meetingBriefing}\`,
  personResearch: \`${prompts.personResearch}\`,
  orgResearch: \`${prompts.orgResearch}\`,
  inboxRouting: \`${prompts.inboxRouting}\`,
  research: \`${prompts.research}\`,
};
`;

fs.writeFileSync(outputFile, tsContent, "utf-8");
console.log(`[GSD] ✓ Generated ${outputFile}`);
